/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Administrator
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        ID = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        Cliente = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        servico = new javax.swing.JLabel();
        jComboboxServico = new javax.swing.JComboBox<>();
        Valor = new javax.swing.JLabel();
        TextValor = new javax.swing.JTextField();
        Data = new javax.swing.JLabel();
        TextFormateData = new javax.swing.JTextField();
        Hora = new javax.swing.JLabel();
        TextFormateHora = new javax.swing.JTextField();
        Observações = new javax.swing.JLabel();
        TextObservacao = new javax.swing.JTextField();
        BotaoAgendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 40));

        textID.setEditable(false);
        textID.setText("0");
        textID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 260, 30));

        Cliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setText("Cliente");
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, 40));

        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 260, 30));

        servico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        servico.setForeground(new java.awt.Color(255, 255, 255));
        servico.setText("Serviço");
        getContentPane().add(servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 80, 40));

        jComboboxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboboxServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboboxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 260, 30));

        Valor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 255, 255));
        Valor.setText("Valor R$");
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 80, 40));

        TextValor.setText("0");
        getContentPane().add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 250, 30));

        Data.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Data.setForeground(new java.awt.Color(255, 255, 255));
        Data.setText("Data");
        getContentPane().add(Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, 40));

        TextFormateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormateDataActionPerformed(evt);
            }
        });
        getContentPane().add(TextFormateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 250, 30));

        Hora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("Hora");
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 80, 40));

        TextFormateHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormateHoraActionPerformed(evt);
            }
        });
        getContentPane().add(TextFormateHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 250, 30));

        Observações.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Observações.setForeground(new java.awt.Color(255, 255, 255));
        Observações.setText("Observações");
        getContentPane().add(Observações, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 110, 40));

        TextObservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextObservacaoActionPerformed(evt);
            }
        });
        getContentPane().add(TextObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 640, 370));

        BotaoAgendar.setBackground(new java.awt.Color(153, 153, 0));
        BotaoAgendar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotaoAgendar.setForeground(new java.awt.Color(242, 242, 242));
        BotaoAgendar.setText("Agenda");
        BotaoAgendar.setActionCommand("Agendar");
        BotaoAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 640, 60));

        TableAgendamentos.setAutoCreateRowSorter(true);
        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jScrollPane1.setViewportView(TableAgendamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 1140, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setMinimumSize(new java.awt.Dimension(640, 480));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 1270, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/AgendaFundo.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 960));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFormateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormateDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormateDataActionPerformed

    private void TextFormateHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormateHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormateHoraActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void TextObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextObservacaoActionPerformed

    private void jComboboxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboboxServicoItemStateChanged

        this.controller.atualizaValor();
    }//GEN-LAST:event_jComboboxServicoItemStateChanged

    private void BotaoAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendarActionPerformed
      this.controller.agendar();
    }//GEN-LAST:event_BotaoAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAgendar;
    private javax.swing.JLabel Cliente;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Observações;
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JTextField TextFormateData;
    private javax.swing.JTextField TextFormateHora;
    private javax.swing.JTextField TextObservacao;
    private javax.swing.JTextField TextValor;
    private javax.swing.JLabel Valor;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboboxServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel servico;
    private javax.swing.JTextField textID;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
       this.controller.atualizaTabela();
       this.controller.atualizaCliente();
       this.controller.atualizaServico();
       this.controller.atualizaValor();
           }

    public JTable getTableAgendamentos() {
        return TableAgendamentos;
    }

    public void setTableAgendamentos(JTable TableAgendamentos) {
        this.TableAgendamentos = TableAgendamentos;
    }

    public JComboBox<String> getjComboBoxCliente() {
        return jComboBoxCliente;
    }

    public void setjComboBoxCliente(JComboBox<String> jComboBoxCliente) {
        this.jComboBoxCliente = jComboBoxCliente;
    }

    public JComboBox<String> getjComboboxServico() {
        return jComboboxServico;
    }

    public void setjComboboxServico(JComboBox<String> jComboboxServico) {
        this.jComboboxServico = jComboboxServico;
    }

    public JTextField getTextValor() {
        return TextValor;
    }

    public void setTextValor(JTextField TextValor) {
        this.TextValor = TextValor;
    }

    public JTextField getTextFormateData() {
        return TextFormateData;
    }

    public void setTextFormateData(JTextField TextFormateData) {
        this.TextFormateData = TextFormateData;
    }

    public JTextField getTextFormateHora() {
        return TextFormateHora;
    }

    public void setTextFormateHora(JTextField TextFormateHora) {
        this.TextFormateHora = TextFormateHora;
    }

    public JTextField getTextObservacao() {
        return TextObservacao;
    }

    public void setTextObservacao(JTextField TextObservacao) {
        this.TextObservacao = TextObservacao;
    }

    public JTextField getTextID() {
        return textID;
    }

    public void setTextID(JTextField textID) {
        this.textID = textID;
    }
    
    
    
}
